version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rafael
      MYSQL_DATABASE: msvc_partners
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: rafael
      POSTGRES_DB: msvc_books
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring


  msvc-pertners:
    container_name: msvc-pertners
    image: rafaeljuy/partners:latest
#    build:
#      context: ./
#      dockerfile: ./msvc_partners/Dockerfile
    ports:
      - "8002:8002"
    env_file: ./msvc_partners/.env
    networks:
      - spring
    depends_on:
      - mysql8
      - msvc-books
    restart: always

  msvc-books:
    container_name: msvc-books
    image: rafaeljuy/books:latest
#    build:
#      context: ./
#      dockerfile: ./msvc_books/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./msvc_books/.env
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring