package com.msvc.partners.exception;

public class ModelKeyAutogeneratedException extends RuntimeException{
    public ModelKeyAutogeneratedException(String message) {
        super(message);
    }
}
